<?php

declare(strict_types=1);

/*
 * ReloadlySdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReloadlySdkLib\Models;

use stdClass;

class ReloadlyAirtimeFxRatesRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $operatorId;

    /**
     * @var string
     */
    private $amount;

    /**
     * @param string $operatorId
     * @param string $amount
     */
    public function __construct(string $operatorId, string $amount)
    {
        $this->operatorId = $operatorId;
        $this->amount = $amount;
    }

    /**
     * Returns Operator Id.
     */
    public function getOperatorId(): string
    {
        return $this->operatorId;
    }

    /**
     * Sets Operator Id.
     *
     * @required
     * @maps operatorId
     */
    public function setOperatorId(string $operatorId): void
    {
        $this->operatorId = $operatorId;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): string
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @required
     * @maps amount
     */
    public function setAmount(string $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['operatorId'] = $this->operatorId;
        $json['amount']     = $this->amount;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
