<?php

declare(strict_types=1);

/*
 * ReloadlySdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReloadlySdkLib\Models;

use stdClass;

class ReloadlyUtilityPaymentsPayBillRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $subscriberAccountNumber;

    /**
     * @var int
     */
    private $amount;

    /**
     * @var int
     */
    private $billerId;

    /**
     * @var bool
     */
    private $useLocalAmount;

    /**
     * @param string $subscriberAccountNumber
     * @param int $amount
     * @param int $billerId
     * @param bool $useLocalAmount
     */
    public function __construct(string $subscriberAccountNumber, int $amount, int $billerId, bool $useLocalAmount)
    {
        $this->subscriberAccountNumber = $subscriberAccountNumber;
        $this->amount = $amount;
        $this->billerId = $billerId;
        $this->useLocalAmount = $useLocalAmount;
    }

    /**
     * Returns Subscriber Account Number.
     */
    public function getSubscriberAccountNumber(): string
    {
        return $this->subscriberAccountNumber;
    }

    /**
     * Sets Subscriber Account Number.
     *
     * @required
     * @maps subscriberAccountNumber
     */
    public function setSubscriberAccountNumber(string $subscriberAccountNumber): void
    {
        $this->subscriberAccountNumber = $subscriberAccountNumber;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): int
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @required
     * @maps amount
     */
    public function setAmount(int $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Biller Id.
     */
    public function getBillerId(): int
    {
        return $this->billerId;
    }

    /**
     * Sets Biller Id.
     *
     * @required
     * @maps billerId
     */
    public function setBillerId(int $billerId): void
    {
        $this->billerId = $billerId;
    }

    /**
     * Returns Use Local Amount.
     */
    public function getUseLocalAmount(): bool
    {
        return $this->useLocalAmount;
    }

    /**
     * Sets Use Local Amount.
     *
     * @required
     * @maps useLocalAmount
     */
    public function setUseLocalAmount(bool $useLocalAmount): void
    {
        $this->useLocalAmount = $useLocalAmount;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['subscriberAccountNumber'] = $this->subscriberAccountNumber;
        $json['amount']                  = $this->amount;
        $json['billerId']                = $this->billerId;
        $json['useLocalAmount']          = $this->useLocalAmount;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
