<?php

declare(strict_types=1);

/*
 * ReloadlySdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ReloadlySdkLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const AUTHENTICATION = 'Authentication';

    public const GIFT_CARDS = 'Gift Cards';

    public const UTILITY_PAYMENTS = 'Utility Payments';

    public const AIRTIME = 'Airtime';
}
